### ISSUE TITLE
Hover video is split in the middle and playing 2 videos at the same time

### ISSUE THREAD

**Issue by vreddi** [sukritchhabra/YouTubeHover#42]
Repro Steps:
1) Go to youtube.com
2) On the top right corner of the thumbnail there is a 'watch later' button.
3) Enter the video thumbnail area with your mouse directly on the watch later button.

When you follow the above steps you would see the following bug:
<img width="237" alt="screen shot 2018-01-30 at 11 00 07 pm" src="https://user-images.githubusercontent.com/6148930/35609332-ba4f98c0-0611-11e8-8a3b-08af588b5f3a.png">
<img width="257" alt="screen shot 2018-01-30 at 10 59 54 pm" src="https://user-images.githubusercontent.com/6148930/35609347-c65333de-0611-11e8-99fc-763229752c40.png">

**Comment by sukritchhabra** [comment]
Had two instances of YoutubeHover, one local and one from the store.

**Comment by vreddi** [comment]
Thanks for clearing the issue out 👍
